import type { Metadata } from "next";
import "./globals.css";
// import Footer from "@/app/components/layout/Footer";
// import Navbar from "@/app/components/layout/Navbar";
import SessionProviderWrapper from "@/app/SessionProviderWrapper";
import { auth } from "../../auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {

  const session = await auth();

  return (
    <html lang="fr" data-theme="light">
      <body className={`antialiased`}>

      <SessionProviderWrapper session={session}>
        {/* <Navbar/> */}
        {children}
        {/* <Footer/> */}
      </SessionProviderWrapper>


      </body>
    </html>
  );
}
